ALL: &ALL
  # For encrypting passwords and email verification params
  crypt:
    password: 'Digest::MD5.hexdigest("#{password}#{salt}")'
    verifier: 'Digest::MD5.hexdigest(email.to_s)[0..9]'
  # Mailgun API keys
  mailgun:
    password: 32pw166im7f9
    secret: key-1uyak4ijwrw1v1xcu1ggdo3eq954mi21
    public: pubkey-1oo8fl2--5ghabi12k32boslf3-576x3
  # For obfuscating Paperclip URLs
  paperclip: 47fa03579472680906e06a0533c16ede02c68ecb904a386a9dd3beb73c68b34c9e8fc0a0ef0a87193d013b5d32768a5f57b03279f7bf004055e0e017d3645de6
  # For importing legacy data from the ratings database
  ratings_db:
    host: localhost
    database: ratings_development
    username: username
    password: password
    encoding: utf8
  # Valid characters in a season ticket and how to reorder them
  season_ticket:
    base: HAgDXP7BcK3fmzh2CaMEdZxyrTWL9tknNe84G6bRwpYF
    shuffle: str.reverse
  # Stripe keys
  stripe:
    public: pk_test_aYo71Qp4R1XBgsQ1ObaE8CpM
    secret: sk_test_5ay80yu1hJb45gV9ul6fb2zt

development:
  <<: *ALL
  secret_key_base: a470108862849c7a2023930175416a48ef185a70eb32bddc37fbf6d93ce0b6cd0d374de49fcace739a2508cc963e72f7468ddf549386eb805cf02d539d4410fa

test:
  <<: *ALL
  secret_key_base: c7dbeee354d2010116c30a3d21545d2b3336adc2049cee9350d3cb49126ee31926a0352adbbfc381d5c32b47d48500d2a043421eab29fb7d622330548ca6df77
